language: ruby

script:
  - bundle exec middleman build --clean
 
deploy:
  local_dir: build
  target_branch: gh-pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
